spring:
    application:
      name: springboot-mybatisplus
    # DataSource Config
    datasource:
      driver-class-name: org.h2.Driver
      username: root
      password: test
      #url: jdbc:h2:~/test
    sql:
      init:
        schema-locations: classpath:db/schema-h2.sql
        data-locations: classpath:db/data-h2.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # mysql的关键字标志 `
      #column-format: "`%s`"
      # h2关键字标志
      column-format: "'%s'"