spring:
  application:
    name: springboot-mybatisplus
    # DataSource Config
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: test
    #url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1'
    #url: jdbc:h2:~/test
    #url: jdbc:h2:mem:test
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
  h2:
    console:
      # http://localhost:8080/h2-console
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # mysql的关键字标志 `
      #column-format: "`%s`"
      # h2关键字标志
      column-format: "'%s'"