server:
  port: 8080
  session:
    timeout: 7200

##spring Setting
spring:
    application:
        name: mysqldemo
    datasource:
      #使用druid连接池
      type: com.alibaba.druid.pool.DruidDataSource

master-db:
  datasource:
    druid: #德鲁伊
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.41.66:3310/gpoints?characterEncoding=utf8&useSSL=false
      username: gpoints
      password: Aa#123456
      initial-size: 2
      max-active: 50
      min-idle: 5
      max-wait: 60000 # 60s
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 60 # 60s
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      # min-evictable-idle-time-millis: 60000
      # max-evictable-idle-time-millis: 90000
      filters: stat,wall
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        # url-pattern:
        # exclusions:
        # session-stat-enable: true
        # session-stat-max-count:
        # principal-session-name:
        # principal-cookie-name:
        # profile-enable:
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # url-pattern:
        reset-enable: false
        login-username: druid
        login-password: druid
        #allow:
        #deny:
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      #aop-patterns: # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      # 如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
### 日志配置
log:
  level: debug